# yaml表示以上对象
person:
  userName: zhangsan
  boss: false
  birth: 2019/12/12 20:12:33
  age: 18
  pet:
    name: tomcat
    weight: 23.4
  interests: [篮球,游泳]
  animal:
    - jerry
    - mario
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [131,140,148]
    chinese: {first: 128,second: 136}
  salarys: [3999,4999.98,5999.99]
  allPets:
    sick:
      - {name: tom}
      - {name: jerry,weight: 47}
    health: [{name: mario,weight: 47}]

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql.qctc.com:3306/js_produce?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
#    username: js_produce
#    password: js_produce
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://mysql.eboss.qctc.com:5236/LXDD_YXFS_QCTC
    username: LXDD_YXFS_QCTC
    password: Qctc.6608

    druid:
      aop-patterns: com.example.springboot.*  #监控SpringBean
      filters: stat,wall,slf4j     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
#          slow-sql-millis: 100
#          logSlowSql: true
          enabled: true
        wall:
          enabled: true
#          config:
#            drop-table-allow: false

  redis:
#    database: ${redis.database}
    host: 127.0.0.1
    port: 6379
    password: redis@123
    pool:
      max-active: 200
      max-wait: 10
      max-idle: 100
      min-idle: 10
    timeout: 5000


logging:
  level:
    root: INFO
    com.example.springboot: INFO
    com.alibaba.druid.pool.DruidDataSource: DEBUG
    org.springframework.jdbc.core.JdbcTemplate:  DEBUG

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'